### ISSUE TITLE
915Mhz Question

### ISSUE THREAD

**Issue by Tokter** [3s1d/fanet-stm32#14]
What are the plans for FANET outside of Europe?

On the Skytraxx 2.1 product page (https://en.skytraxx.eu/product-page/skytraxx-2-1) it states:

_FANET and FLARM broadcast on 868Mhz. Outside the EU, FANET must be deactivated.
The frequency is also planned to be expanded to 915Mhz for 2020._

The Skytraxx 4.0 product page does not mention anything about frequencies yet.

I know there are other vario manufacturers that use your module to provide the Fanet/Flarm functionality, which then in turn have the same limitation of only working/be legal in Europe. Without explaining that limitation as transparently on their websites.

Is there any hope for people like me that would need the 915MHz option, or is that market just too small to bother?

Thanks,
Markus

**Comment by 3s1d** [comment]
Hi,
well... Covid happened. We still plan to enable 9xxMhz for FANET. It's very import to us. However, due to the chip shortage and so on, we currently do not have time to figure out all the 'little' details for each country (like: frequency, power, bandwidth, duty cycle, and many more).  If you can provide a list or anything else this would greatly boost the development. Thanks,
Juergen

**Comment by Tokter** [comment]
I'm not an expert in that, but I tried to gather at least some of the relevant information. Thanks for the update!

# US

## Frequency spectrum
902Mhz - 928MHz

## Bandwidth
I think you're using 250kHz, so this applies:
_if the 20 dB bandwidth of the hopping channel is 250 kHz or greater, the system shall use at least 25 hopping frequencies_

## Duty Cycle
For 250kHz bandwidth, this applies:
_the average time of occupancy on any frequency shall not be greater than 0.4 seconds within a 10 second period._

## Power
_0.25 watts for systems employing less than 50 hopping channels, but at least 25 hopping channels_

This assumes an antenna with no more than 6dBi gain:
 _The conducted output power limit specified in paragraph (b) of this section is based on the use of antennas 
with directional gains that do not exceed 6 dBi. Except as shown in paragraph (c) of this section, if transmitting antennas of directional gain greater than 6 dBi are used, the conducted output power from the intentional radiator shall be reduced below the stated values in paragraphs (b)(1), (b)(2), and (b)(3) of this section, as appropriate, by the amount in dB that the 
directional gain of the antenna exceeds 6 dBi_

## Links
Regulation: https://www.govinfo.gov/content/pkg/CFR-2013-title47-vol1/pdf/CFR-2013-title47-vol1-sec15-247.pdf
ISM-Band and Short Range Device Regulatory Compliance Overview: https://www.ti.com/lit/an/swra048/swra048.pdf

**Comment by 3s1d** [comment]
Hi,

thanks for the information. Guess I have to start somewhere... 

As I recall it correctly there is some kind of threshold were one does not need to do frequency hopping, right?! I'd hate to implement this. Specially for devices w/o GPS this is not simple... (This is the only thing currently holding me back.)

Right now the duty cycle is below 1%, all antenna gains are <4dBi, and we are transmitting with 14dBm (25mW). Do I recall it correctly that we'd simple would have to increase the used bandwidth to >250kHz and then we are fine?

Can you implement the driver? Do you want to do testing, as it's not legal in my area :)
What kind of device are you using?  -> Contact me via mail.

Juergen

**Comment by ifrew** [comment]
Hi Jurgen,

Hope you are doing well. This is Iain from Seattle. I worked with Phil on the Airwhere project, met with you at Kossen and have since developed my little vario and fanet device to a fully functional working prototype based on esp32. I thought i'd update the old fanet software I ported from your original code to the latest version you have here and so came across this comment. I investigated getting my device certified over here and contacted a lab that could do FCC testing in Chicago. Cost was around $4,500 so not too spendy. The cost for EU certification where there is more of a market, at least for me, was spendy!

M5Vario |  FCC Part 15 Testing & Certification (FCC Part 15C: 15.203, 15.205, 15.207, 15.209, 15.247, 15.212 & 2.1091 (RF Exposure)) - $4,500 
M5Vario | CE Testing & Certification (CE RED | EN 300 220-1 & -2 v3.1.1 & EN 50663:2017) - $4,200
M5Vario | CE Testing & Certification (CE EMC | EN 301 489-1 v2.2.0 & EN 301 489-3 v3.1.1) - $2,600
M5Vario | CE Testing & Certification (CE LVD | EN 62368-1:2014+A11:2017) - $3,500


However, I gleamed some good information from them. You do not need to implement frequency hopping I'm glad to report as long as you use a frequency bandwidth of 500Khz. The FCC does not care about dwell time at all over here they said, so you can increase the spreading factor as you want. I was surprised by this but they assured me that would be legal. They also wouldn't do frequency hopping tests for me due to the test equipment they would need to setup as the market for using that is so small. So currently I use as my parameters over here, 

                sx1276.begin(916040);
                sx1276.setPreambleLength(5);	 
          sx1276.setSignalBandwidth(500E3);
		sx1276.setSpreadingFactor(10);
		sx1276.setTimeout(5);
		sx1276.setCodingRate4(5);
		sx1276.enableCrc();
		sx1276.setSyncWord(0xF1);

These should be good for you and it would be great if you used the same parameters for the USA moving forwards. I do know that XCTracer Maxx use freq hopping and got FCC tested going down that route. If you do want to get setup in the USA then I'd be happy to help out, maybe even be your rep over here, just send me a mail.

Cheers

Iain

**Comment by 3s1d** [comment]
Hi iFrew,

I fully missed your posed for years... SORRY!
Meanwhile we have defined non EU frequencies. Please see fmac.h.
Did you stick to 916Mhz or maybe have you moved the frequency? We should find a common base somehow (thou' the software is already rolled out to thousends of devices)...

Bests,
Juergen

**Comment by ifrew** [comment]
Not a problem Juergen.

I don't have as many devices as you. We exchanged email about this relatively recently directly and I know the frequencies you changed. I don't have thousands of devices but enough for me not to change it. My device is only used locally by pilots here in the NW USA anyway as they were mainly prototypes. Have you got a lot of them now being used in the USA?

Cheers

Iain

**Comment by 3s1d** [comment]
Fanet new supports 9xxMhz freq outside of the EU.
